Document: awesant
Title: Debian awesant Manual
Author: <insert document author here>
Abstract: This manual describes what awesant is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/awesant/awesant.sgml.gz

Format: postscript
Files: /usr/share/doc/awesant/awesant.ps.gz

Format: text
Files: /usr/share/doc/awesant/awesant.text.gz

Format: HTML
Index: /usr/share/doc/awesant/html/index.html
Files: /usr/share/doc/awesant/html/*.html
